name: Website and Supabase Keep-Alive
on:
  schedule:
    - cron: '0 */24 * * *'  # Every 24 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Website
        run: |
          echo "Pinging website homepage..."
          curl -X GET "https://manojnarender.vercel.app/" -v
          
      - name: Ping Testimonials Section
        run: |
          echo "Pinging testimonials section..."
          curl -X GET "https://manojnarender.vercel.app/#testimonials" -v
          
      - name: Check Supabase Connection
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_KEY" ]; then
            echo "⚠️ Warning: Supabase credentials not configured in secrets"
          else
            echo "Checking Supabase connection..."
            RESPONSE=$(curl -s -X GET "$SUPABASE_URL/rest/v1/testimonials?select=id,name,role&approved=eq.true&limit=1" \
              -H "apikey: $SUPABASE_KEY" \
              -H "Authorization: Bearer $SUPABASE_KEY")
            
            if [[ "$RESPONSE" == "["* ]]; then
              echo "✅ Successfully connected to Supabase"
              if [[ "$RESPONSE" == "[]" ]]; then
                echo "ℹ️ No approved testimonials found in the database"
              else
                echo "✅ Testimonials are available in the database"
              fi
            else
              echo "⚠️ Warning: Failed to connect to Supabase or received unexpected response"
              echo "Response: $RESPONSE"
            fi
          fi
          
      - name: Check Website Response
        run: |
          RESPONSE=$(curl -s "https://manojnarender.vercel.app/")
          if [[ "$RESPONSE" == *"Manoj Narender"* ]]; then
            echo "Website is up and running!"
            
            # Rest of your existing checks...