name: Website and Supabase Keep-Alive
on:
  schedule:
    - cron: '0 */24 * * *'  # Every 24 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Website
        run: |
          echo "Pinging website homepage..."
          curl -X GET "https://manojnarender.vercel.app/" -v
          
      - name: Ping Testimonials Section
        run: |
          echo "Pinging testimonials section..."
          curl -X GET "https://manojnarender.vercel.app/#testimonials" -v
          
      - name: Check Website Response
        run: |
          RESPONSE=$(curl -s "https://manojnarender.vercel.app/")
          if [[ "$RESPONSE" == *"Manoj Narender"* ]]; then
            echo "Website is up and running!"
            
            # Check for testimonials section existence
            if [[ "$RESPONSE" == *"id=\"testimonials\""* ]]; then
              echo "✅ Testimonials section exists on the page"
              
              # Check for testimonials carousel/container
              if [[ "$RESPONSE" == *"flex absolute left-0 gap-4 py-4"* ]]; then
                # This is the container div for testimonials
                
                # Check if actual testimonial data is loaded
                if [[ "$RESPONSE" == *"data-testimonial-id"* || "$RESPONSE" == *"testimonial-author"* || "$RESPONSE" == *"testimonial-role"* ]]; then
                  echo "✅ Testimonials are loading from the database successfully!"
                else
                  echo "⚠️ Warning: Testimonials container exists but no testimonial data found"
                  echo "This could indicate a Supabase connection issue"
                fi
              else
                echo "⚠️ Warning: Testimonials carousel container not found"
                echo "This could indicate a rendering issue with the testimonials component"
              fi
              
              # Check if the form is present (which should always be there)
              if [[ "$RESPONSE" == *"Enter your name"* && "$RESPONSE" == *"Your role or company name"* ]]; then
                echo "✅ Testimonials form is loading correctly"
              else
                echo "⚠️ Warning: Testimonials form elements not found"
              fi
            else
              echo "⚠️ Warning: Testimonials section not found on the page"
            fi
          else
            echo "⚠️ Warning: Website might be down or changed"
          fi