name: Website and Supabase Keep-Alive
on:
  schedule:
    - cron: '0 */24 * * *'  # Every 24 hours
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Website
        run: |
          echo "Pinging website homepage..."
          curl -X GET "https://manojnarender.vercel.app/" -v
          
      - name: Ping Testimonials Section
        run: |
          echo "Pinging testimonials section..."
          curl -X GET "https://manojnarender.vercel.app/#testimonials" -v
          
      - name: Check Website Response
        run: |
          RESPONSE=$(curl -s "https://manojnarender.vercel.app/")
          if [[ "$RESPONSE" == *"Manoj Narender"* ]]; then
            echo "Website is up and running!"
            
            # Check for testimonials content
            if [[ "$RESPONSE" == *"testimonial-card"* || "$RESPONSE" == *"testimonial-message"* || "$RESPONSE" == *"testimonial-author"* ]]; then
              echo "✅ Testimonials are loading successfully!"
            else
              echo "⚠️ Warning: Website is up but testimonials might not be loading"
              echo "This could indicate a Supabase connection issue"
            fi
          else
            echo "⚠️ Warning: Website might be down or changed"
          fi