name: Supabase Keep-Alive
on:
  schedule:
    - cron: '0 0 */5 * *'  # Every 6 days at midnight
  workflow_dispatch:        # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Database
        run: |
          curl -X GET "${{ secrets.APP_URL }}/api/cron/keep-alive" -v  # Added -v for verbose output